task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]
  verbose: False

num_classes: ~
remap_mscoco_category: False

yolo_root: ~
yolo_data_file: ~

train_dataloader:
  type: DataLoader
  dataset:
    type: YOLODetection
    split: train
    return_masks: False
    strict: True
    validate_on_init: True
  shuffle: True
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: YOLODetection
    split: val
    return_masks: False
    strict: True
    validate_on_init: True
  shuffle: False
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
